replicaCount: 2

image:
  repository: s1ds1ngh/hello-world-api
  tag: "1.0"
  pullPolicy: IfNotPresent

service:
  port: 80
  targetPort: 8080
  nodePort: 30080

ingress:
  host: hello-world.info

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "500m"
