apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080 # Port the service listens on
      targetPort: 8080 # Port the backend container listens on
  type: ClusterIP # Internal service for backend

